# Generated by Django 5.0.6 on 2024-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_photo'),
        ('job', '0002_remove_job_customer_remove_job_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='jobs',
            field=models.ManyToManyField(related_name='customer', to='job.job'),
        ),
    ]
