# Generated by Django 5.0.6 on 2024-07-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='salary',
        ),
    ]
