# Generated by Django 5.0.6 on 2024-07-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_customer_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='images/defaultImage/customer.jpg', null=True, upload_to='images/customers/'),
        ),
    ]
