# Generated by Django 5.0.6 on 2024-07-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='jobs',
        ),
    ]
