# Generated by Django 5.0.6 on 2024-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
