# Generated by Django 5.0.6 on 2024-07-01 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forauth', '0005_initial'),
        ('freelancer', '0002_alter_freelancer_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelancer',
            options={'verbose_name': 'Freelancer', 'verbose_name_plural': 'Freelancers'},
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='myuser_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='freelancer_profile', serialize=False, to='forauth.myuser'),
        ),
    ]
