# Generated by Django 5.0.6 on 2024-07-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_alter_freelancer_options_alter_freelancer_myuser_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
