# Generated by Django 5.0.6 on 2024-07-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_alter_freelancer_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
