# Generated by Django 5.0.6 on 2024-07-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_alter_freelancer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/freelancers/'),
        ),
    ]
