# Generated by Django 5.0.6 on 2024-07-03 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0009_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='freelancers', to='freelancer.profession'),
            preserve_default=False,
        ),
    ]
