# Generated by Django 5.0.6 on 2024-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0010_freelancer_profession'),
        ('job', '0002_remove_job_customer_remove_job_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='job',
            field=models.ManyToManyField(related_name='freelancer', to='job.job'),
        ),
    ]
