# Generated by Django 5.0.6 on 2024-07-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0011_freelancer_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
