# Generated by Django 5.0.6 on 2024-07-09 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0012_freelancer_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancers', to='freelancer.profession'),
        ),
    ]
