# Generated by Django 5.0.6 on 2024-07-01 14:49

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forauth', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminka',
            fields=[
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('myuser_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='admin_profile', serialize=False, to='forauth.myuser')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
            bases=('forauth.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
