# Generated by Django 5.0.6 on 2024-06-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('S', 'student'), ('C', 'customer'), ('A', 'admin')], max_length=50),
        ),
    ]
