# Generated by Django 5.0.6 on 2024-07-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forauth', '0002_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('F', 'freelancer'), ('C', 'customer'), ('A', 'admin')], max_length=50),
        ),
    ]
