# Generated by Django 5.0.6 on 2024-07-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forauth', '0003_alter_myuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
