# Generated by Django 5.0.6 on 2024-07-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_alter_customer_photo'),
        ('freelancer', '0010_freelancer_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('process', models.CharField(choices=[(0, 'start'), (1, 'process'), (2, 'end')], max_length=10)),
                ('customer', models.ManyToManyField(related_name='jobs', to='customer.customer')),
                ('freelancer', models.ManyToManyField(related_name='jobs', to='freelancer.freelancer')),
            ],
        ),
    ]
