# Generated by Django 5.0.6 on 2024-07-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_job_customer_remove_job_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='process',
            field=models.CharField(choices=[('0', 'start'), ('1', 'process'), ('2', 'end')], max_length=10),
        ),
    ]
