# Generated by Django 5.0.6 on 2024-07-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='process',
            field=models.CharField(choices=[('0', 'Start'), ('1', 'Process'), ('2', 'Done')], max_length=10),
        ),
    ]
