# Generated by Django 5.0.6 on 2024-07-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='process',
            field=models.CharField(choices=[('0', 'Start'), ('1', 'Process'), ('2', 'Done')], default='0', max_length=10),
        ),
    ]
