# Generated by Django 5.0.6 on 2024-07-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0013_alter_freelancer_profession'),
        ('job', '0006_job_description_job_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobs', to='freelancer.skills'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
