# Generated by Django 5.0.6 on 2024-07-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0013_alter_freelancer_profession'),
        ('job', '0008_job_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', to='freelancer.skills'),
        ),
    ]
