# Generated by Django 5.0.6 on 2024-07-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='price',
            field=models.IntegerField(default=150),
        ),
    ]
